### ISSUE TITLE
mhi wf-rac module traces?

### ISSUE THREAD

**Issue by RobertJansen1** [absalom-muc/MHI-AC-Trace#3]
I saw there is a new wifi module from Mitsubishi, the wf-rac. From the demo in the app it seems possible to control swing and fan speeds. I have been using the esp module with great pleasure and would like to donate if someone thinks it is possible to capture the necessary code from this mhi wifi module, and merge the possibilities into the esp product.

I have no knowledge yet on how to do such a thing myself.

**Comment by absalom-muc** [comment]
Thanks for the offer @RobertJansen1 , appreciate it. I expect to receive the WF-RAF in the next weeks. Then I'll try to find out the missing swing/fan control.

**Comment by absalom-muc** [comment]
I believe the issue was addressed, therefore closed. If there are further questions, please feel free to re-open it.
