### ISSUE TITLE
Toggle in MISO frame

### ISSUE THREAD

**Issue by glsf91** [absalom-muc/MHI-AC-Trace#4]
When using this trace software I got a lot of log lines because a toggle of DB14 in the MISO frame.
Maybe you can skip this toggle like you did with the room temperature in the MOSI frame.

With this I removed the toggle:

```
      if (MISO_frame[byte_cnt] != MISO_byte) {
        MISO_frame[byte_cnt] = MISO_byte;
        // Ignore toggle of MISO DB14 
        if ((byte_cnt != 17)& (byte_cnt != CBH) & (byte_cnt != CBL) )
           MISO_diff = true;
      }
```

**Comment by absalom-muc** [comment]
added to 1.52
